openapi: 3.0.3
info:
  title: OpenDataDiscovery API Contract
  version: 0.0.1
  description: OpenDataDiscovery API Contract
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /ingestion/entities:
    post:
      description: Ingests list of data entities
      operationId: postDataEntityList
      tags:
        - OpenDataDiscoveryIngestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataEntityList'
      responses:
        '201':
          description: Created

  /ingestion/entities/datasets/stats:
    post:
      description: Ingests list of stats for data sets
      operationId: postDataSetStatsList
      tags:
        - OpenDataDiscoveryIngestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DatasetStatisticsList'
      responses:
        '201':
          description: Created

  /ingestion/datasources:
    post:
      description: Creates data sources in the target catalog
      operationId: createDataSource
      tags:
        - OpenDataDiscoveryIngestion
      requestBody: 
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/DataSourceList'
      responses:
        '201':
          description: Created

  /ingestion/alerts:
    post:
      description: Alerts target catalog about ingestion issues
      operationId: createAlerts
      tags:
        - OpenDataDiscoveryIngestion
      requestBody:
        content:
          application/json:
            schema:
              $ref: './entities.yaml/#/components/schemas/IngestionAlertList'
      responses:
        '201':
          description: Created
  
  /ingestion/entities/degs/children:
    get:
      description: Searches for data entities in the target catalog by oddrn of a DEG they are currently part of
      operationId: getDataEntitiesByDEGOddrn
      tags:
        - OpenDataDiscoveryIngestion
      parameters:
        - name: oddrn
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './entities.yaml/#/components/schemas/CompactDataEntityList'